### ISSUE TITLE
Whether to support concave polygons

### ISSUE THREAD

**Issue by A-lucky-boy** [sasam2/nesting2#1]
Hello author, thank you very much for the program you provided. I have a small question. Does this program support concave polygon layout calculation?

**Comment by sasam2** [comment]
It supports concave polygons and irregular layouts as in the pic below:
![imagem](https://github.com/sasam2/nesting2/assets/33865438/9c0593fa-4d0d-4a4c-892e-22cb40016608)

**Comment by A-lucky-boy** [comment]
> 它支持凹多边形和不规则布局，如下图所示： ![图像](https://user-images.githubusercontent.com/33865438/279693831-a52a85f2-74cc-4e17-ae30-68534297b395.png)

Wow, thank you very much for your reply. I am very interested in the project you provided, and thank you very much for the open source code you provided.

**Comment by A-lucky-boy** [comment]
> 它支持凹多边形和不规则布局，如下图所示： ![图像](https://user-images.githubusercontent.com/33865438/279693831-a52a85f2-74cc-4e17-ae30-68534297b395.png)

Author, I'm sorry to bother you again. I have been compiling according to the 'C++ library' required in your .sln file these days, but many files are always missing. I don't know if it's due to the version. Can you add an introduction in your free time? Could you please explain the version numbers of the ‘C++ libraries’ in the project? Which version of vs is required for compilation? x86 or x64?

**Comment by sasam2** [comment]
Just added to the readme the dependencies you need to provide to build the project:
    CGAL (https://www.cgal.org/)
    freeglut (https://freeglut.sourceforge.net/)
    glew (https://glew.sourceforge.net/)
    glui (https://github.com/libglui/glui)
    opencv (https://opencv.org/)

>  Which version of vs is required for compilation? x86 or x64?
You will have to generate the Visual Studio project for some of the libraries above with CMake (https://cmake.org/). I've been using Visual Studio 2022 and building for x64.

**Comment by A-lucky-boy** [comment]
> 刚刚在自述文件中添加了构建项目所需的依赖项： CGAL ( https://www.cgal.org/ ) freeglut ( https://freeglut.sourceforge.net/ ) glew ( [https://glew. sourceforge.net/](https://glew.sourceforge.net/) ) glui ( https://github.com/libglui/glui ) opencv ( https://opencv.org/ )
> 
> > 编译需要哪个版本的vs？x86 还是 x64？
> 
> 您必须使用 CMake ( https://cmake.org/ ) 为上述某些库生成 Visual Studio 项目。我一直在使用 Visual Studio 2022 并针对 x64 进行构建。

Thank you so much for your reply, you are simply awesome！

**Comment by A-lucky-boy** [comment]
> 刚刚在自述文件中添加了构建项目所需的依赖项： CGAL ( https://www.cgal.org/ ) freeglut ( https://freeglut.sourceforge.net/ ) glew ( [https://glew.sourceforge .net/](https://glew.sourceforge.net/)） glui（https://github.com/libglui/glui） opencv（https://opencv.org/）
> 
> > 编译需要哪个版本的vs？x86 还是 x64？
> 
> 您必须使用 CMake ( https://cmake.org/ ) 来为上述某些库生成 Visual Studio 项目。我一直在使用 Visual Studio 2022 并针对 x64 进行构建。

Hello author, after many days of hard work, I still can't complete the "C++ library" you need for this project, and it keeps prompting that glew, glui and freeglut have problems, and I can't compile the "freeglutd.lib,glui_staticd.lib" you mentioned in the project; And when using x64 for debugging, "glew32.lib" gets an error. Can you share your compiled "C++ Library" file? I don't know if this will make your work difficult, if you can share it conveniently, can you send your file to my gmailbox "luckyboylighthousealliance@gmail.com" thank you very much for your project.

Because I can't run your project right now, I have another idea I don't know if it's okay, I can directly set the coordinate points of the sheet and concave polygons in the program, and then calculate the coordinates of the points after nesting through your program, so that I can open a separate OpenCV program to draw, I don't know if this is feasible?

Looking forward to your reply.

**Comment by sasam2** [comment]
Hi, I added complete build and run instructions here: [https://github.com/sasam2/nesting2/blob/master/How_to_build_and_run.pdf](https://github.com/sasam2/nesting2/blob/master/How_to_build_and_run.pdf)
Please check them out.

**Comment by A-lucky-boy** [comment]
> 您好，我在这里添加了完整的构建和运行说明：https://github.com/sasam2/nesting2/blob/master/How_to_build_and_run.pdf 请查看它们。

Thank you very much for the author's patient help. The program has been successfully run. Thank you for your project. I like your project so much.

**Comment by A-lucky-boy** [comment]
Hello author, thank you very much for your help. I have successfully run your project on the computer, and your program has provided me with great help. Thank you again.




A&nbsp;lucky&nbsp;boy
***@***.***







                       
原始邮件
                       
                     

发件人："sasam2"< ***@***.*** &gt;;

发件时间：2023/11/5 20:12

收件人："sasam2/nesting2"< ***@***.*** &gt;;

抄送人："A-lucky-boy"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [sasam2/nesting2] Whether to support concave polygons (Issue #1)




 
Hi, I added complete build and run instructions here: https://github.com/sasam2/nesting2/blob/master/How_to_build_and_run.pdf
 Please check them out.
